#!/bin/sh


uci set luci.main.lang=zh_cn
uci set system.@system[0].hostname=OpenWrt
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename='Asia/Shanghai'
uci set network.lan.ipaddr=192.168.2.1
uci commit
sed -i 's#downloads.openwrt.org#mirrors.ustc.edu.cn/openwrt#g' /etc/opkg/distfeeds.conf
sed -i 's#openwrt.pool.ntp.org#cn.pool.ntp.org#g' /etc/config/system
